Repository XCSoar/xcsoar-data-content, pull requests merged in 2019-03, with the labels that each got.

#22 Germany Blumberg new frequency
  waypoints/Germany.cup
Labels: data

#21 Belchasse New Frequency based on
  waypoints/Switzerland.cup
Labels: data

#25 Delete United Kingdom.txt
  United Kingdom.txt
Labels: data

#8 Dittingen's New Frequency
  waypoints/Switzerland.cup
Labels: data

#23 Enhance readme
  README.md
Labels: documentation

#29 rename files as android is unable to deal with spaces
  waypoints/Bosnia_And_Herzegovina.cup
  waypoints/Czech_Republic.cup
  waypoints/Dominican_Republic.cup
  waypoints/Libyan_Arab_Jamabiriya.cup
  waypoints/New_Zealand.cup
  waypoints/Russian_Federation.cup
  waypoints/South_Africa.cup
  waypoints/Sri_Lanka.cup
  waypoints/Syrian_Arab_Republic.cup
  waypoints/United_Kingdom.cup
  waypoints/United_States.cup
Labels: breaking

#15 Update CzechRepublic and Slovakia waypoints, Add Czech Republic airspace
  airspaces/CZ2018_ALL.txt
  waypoints/Czech_Republic.cup
  waypoints/Slovakia.cup
Labels: data
